from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt
from PyQt5.QtWidgets import *
from main_ui import Ui_MainWindow
import requests

class MainWindow(QWidget):
    def __init__(self):
        super().__init__()
        self.setObjectName("MainWindow")
        self.resize(483, 569)
        self.centralwidget = QtWidgets.QWidget(self)
        self.centralwidget.setObjectName("centralwidget")

        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(200, 530, 81, 31))
        self.pushButton.setObjectName("pushButton")

        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 10, 441, 151))
        self.groupBox.setStyleSheet("background-color:rgba(255,255,255,1)")
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(20, 20, 71, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(110, 20, 21, 21))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(250, 20, 21, 21))
        self.label_3.setObjectName("label_3")
        self.line = QtWidgets.QFrame(self.groupBox)
        self.line.setGeometry(QtCore.QRect(20, 40, 401, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(130, 20, 101, 21))
        self.label_4.setStyleSheet("border: 1px solid black; ")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(280, 20, 101, 21))
        self.label_5.setStyleSheet("border: 1px solid black; ")
        self.label_5.setObjectName("label_5")
        self.line_2 = QtWidgets.QFrame(self.groupBox)
        self.line_2.setGeometry(QtCore.QRect(20, 80, 401, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(20, 60, 71, 21))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(110, 60, 21, 21))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(130, 60, 101, 21))
        self.label_8.setStyleSheet("border: 1px solid black; ")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setGeometry(QtCore.QRect(280, 60, 101, 21))
        self.label_9.setStyleSheet("border: 1px solid black; ")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        self.label_10.setGeometry(QtCore.QRect(250, 60, 21, 21))
        self.label_10.setObjectName("label_10")
        self.line_3 = QtWidgets.QFrame(self.groupBox)
        self.line_3.setGeometry(QtCore.QRect(20, 130, 401, 20))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.label_11 = QtWidgets.QLabel(self.groupBox)
        self.label_11.setGeometry(QtCore.QRect(20, 110, 71, 21))
        self.label_11.setObjectName("label_11")
        self.line_4 = QtWidgets.QFrame(self.groupBox)
        self.line_4.setGeometry(QtCore.QRect(20, 120, 401, 20))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.label_12 = QtWidgets.QLabel(self.groupBox)
        self.label_12.setGeometry(QtCore.QRect(20, 100, 71, 21))
        self.label_12.setObjectName("label_12")
        self.frame = QtWidgets.QFrame(self.groupBox)
        self.frame.setGeometry(QtCore.QRect(80, 100, 21, 21))
        self.frame.setStyleSheet("background-color: blue;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_13 = QtWidgets.QLabel(self.groupBox)
        self.label_13.setGeometry(QtCore.QRect(120, 100, 31, 21))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.groupBox)
        self.label_14.setGeometry(QtCore.QRect(130, 100, 101, 21))
        self.label_14.setStyleSheet("border: 1px solid black; \n"
"text-align: center;\n"
"color:blue;")
        self.label_14.setObjectName("label_14")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 170, 441, 161))
        self.groupBox_2.setStyleSheet("background-color:rgba(255,255,255,1)")
        self.groupBox_2.setObjectName("groupBox_2")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(20, 340, 441, 161))
        self.groupBox_3.setStyleSheet("background-color:rgba(255,255,255,1)")
        self.groupBox_3.setObjectName("groupBox_3")
        self.textBrowser = QtWidgets.QTextBrowser(self.groupBox_3)
        self.textBrowser.setGeometry(QtCore.QRect(10, 20, 421, 121))
        self.textBrowser.setStyleSheet("background-color: rgb(254, 255, 172);\n"
"color: blue;")
        self.textBrowser.setObjectName("textBrowser")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(290, 530, 81, 31))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(380, 530, 81, 31))
        self.pushButton_4.setObjectName("pushButton_4")

        # self.setCentralWidget(centralwidget)
        # self.actionfishing = QtWidgets.QAction(MainWindow)
        # self.actionfishing.setObjectName("actionfishing")
        # self.actionherbs = QtWidgets.QAction(MainWindow)
        # self.actionherbs.setObjectName("actionherbs")
        # self.actionfishing_2 = QtWidgets.QAction(MainWindow)
        # self.actionfishing_2.setObjectName("actionfishing_2")
        # self.actionherbing = QtWidgets.QAction(MainWindow)
        # self.actionherbing.setObjectName("actionherbing")
        #
        self.retranslateUi(self)
        # QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "시작"))
        self.groupBox.setTitle(_translate("MainWindow", "STATUS"))
        self.label.setText(_translate("MainWindow", "현재 창 크기"))
        self.label_2.setText(_translate("MainWindow", "x :"))
        self.label_3.setText(_translate("MainWindow", "y :"))
        self.label_4.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "X좌표"))
        self.label_5.setText(_translate("MainWindow", "Y좌표"))
        self.label_6.setText(_translate("MainWindow", "마우스 위치"))
        self.label_7.setText(_translate("MainWindow", "x :"))
        self.label_8.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.label_8.setText(_translate("MainWindow", "X좌표"))
        self.label_9.setText(_translate("MainWindow", "Y좌표"))
        self.label_10.setText(_translate("MainWindow", "y :"))
        self.label_11.setText(_translate("MainWindow", "커서 색"))
        self.label_12.setText(_translate("MainWindow", "커서 색"))
        self.label_13.setText(_translate("MainWindow", ":"))
        self.label_14.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.label_14.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">RGB</p></body></html>"))
        self.groupBox_2.setTitle(_translate("MainWindow", "CONTROLLER"))
        self.groupBox_3.setTitle(_translate("MainWindow", "CONSOLE"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
    "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
    "p, li { white-space: pre-wrap; }\n"
    "</style></head><body style=\" font-family:\'Gulim\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
    "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">something is going on...</p></body></html>"))
        self.pushButton_3.setText(_translate("MainWindow", "중지"))
        self.pushButton_4.setText(_translate("MainWindow", "종료"))
        self.actionfishing.setText(_translate("MainWindow", "fishing"))
        self.actionherbs.setText(_translate("MainWindow", "herbs"))
        self.actionfishing_2.setText(_translate("MainWindow", "fishing"))
        self.actionherbing.setText(_translate("MainWindow", "herbing"))
